[build]
  base = "assessment-app"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/config/**"]
  
[dev]
  publish = "public"
  functions = "netlify/functions"
